name: project
description: "project-game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2 #3.8.1

dependencies:
  flutter:
    sdk: flutter
  sudoku_solver_generator: ^2.1.0+1
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  xml: ^6.1.0
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2       # 之後做定位#還不知道功用
  permission_handler: ^11.3.1 #還不知道功用
  flutter_svg: ^2.0.7 #還不知道功用

  three_dart:
    git:
      url: https://github.com/fromeastale/three_dart.git

  flutter_gl:
    git:
      url: https://github.com/wasabia/flutter_gl.git
      ref: 5a46e357fef86cb228096322ea9cec175d301a0f
      path: flutter_gl

dependency_overrides:
  flutter_gl:
    git:
      url: https://github.com/wasabia/flutter_gl.git
      ref: 5a46e357fef86cb228096322ea9cec175d301a0f
      path: flutter_gl

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/maps/map.osm
    - assets/models/map.glb
    - assets/icons/ghost.svg
    - assets/icons/student.svg
    - assets/icons/home.svg
    - assets/icons/nav.svg
    - assets/icons/game.svg
    - assets/icons/info.svg
    - assets/icons/room.svg
    - assets/icons/player.svg
    - assets/icons/random.svg
    - assets/icons/folder.svg
    - assets/icons/btnRandom.svg
    - assets/icons/smile.svg
    - assets/icons/studentSkill_1.svg
    - assets/icons/studentSkill_2.svg
    - assets/icons/studentSkill_3.svg
    - assets/icons/studentSkill_4.svg
    - assets/icons/studentSkill_5.svg
    - assets/icons/studentSkill_6.svg
    - assets/icons/studentSkill_7.svg
    - assets/icons/studentSkill_8.svg
    - assets/icons/ghostSkill_1.svg
    - assets/icons/ghostSkill_2.svg
    - assets/icons/ghostSkill_3.svg
    - assets/icons/ghostSkill_4.svg
    - assets/icons/ghostSkill_5.svg
    - assets/icons/ghostSkill_6.svg
    - assets/icons/ghostSkill_7.svg
    - assets/icons/ghostSkill_8.svg